[package]
name = "libasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libasi-sys = { version = "0.1.0", path = "../libasi-sys" }
log = "0.4"